DISENTANGLER_DECODER_OUTPUT = 'output'
DISENTANGLER_ENCODER_INPUT = 'in'
QUANTIZED_PHYLO_OUTPUT = 'zq_phylo'
DISENTANGLER_CLASS_OUTPUT = 'class'
# DISENTANGLER_ANTICLASS_OUTPUT = 'anti_class'
DISENTANGLER_NON_ATTRIBUTE_TO_ATTRIBUTE_OUTPUT = 'nonattribate_to_attribute'
NON_CLASS_TENSORS = [DISENTANGLER_ENCODER_INPUT, DISENTANGLER_DECODER_OUTPUT, QUANTIZED_PHYLO_OUTPUT, DISENTANGLER_NON_ATTRIBUTE_TO_ATTRIBUTE_OUTPUT]

# CLASS_TENSORS = [DISENTANGLER_CLASS_OUTPUT, DISENTANGLER_ANTICLASS_OUTPUT]
CLASS_TENSORS = [DISENTANGLER_CLASS_OUTPUT]

DATASET_CLASSNAME = 'class_name'

PHYLOCONFIG_KEY = "phylomodel_params"
BASEMODEL_KEY = "basemodel"