DISENTANGLER_DECODER_OUTPUT = 'output'
DISENTANGLER_ENCODER_INPUT = 'in'
QUANTIZED_PHYLO_OUTPUT = 'zq_phylo'
DISENTANGLER_CLASS_OUTPUT = 'class'
QUANTIZED_PHYLO_NONATTRIBUTE_OUTPUT = 'zq_phylo_nonattribute'
DISENTANGLER_NON_ATTRIBUTE_TO_ATTRIBUTE_OUTPUT = 'nonattribate_to_attribute'
DISENTANGLER_NON_ATTRIBUTE_CLASS_OUTPUT = 'anti_classification_classifier_output'
NON_CLASS_TENSORS = [DISENTANGLER_ENCODER_INPUT, DISENTANGLER_DECODER_OUTPUT, QUANTIZED_PHYLO_OUTPUT, DISENTANGLER_NON_ATTRIBUTE_TO_ATTRIBUTE_OUTPUT, QUANTIZED_PHYLO_NONATTRIBUTE_OUTPUT, DISENTANGLER_NON_ATTRIBUTE_CLASS_OUTPUT]

# CLASS_TENSORS = [DISENTANGLER_CLASS_OUTPUT, DISENTANGLER_ANTICLASS_OUTPUT]
CLASS_TENSORS = [DISENTANGLER_CLASS_OUTPUT]  

DATASET_CLASSNAME = 'class_name'

PHYLOCONFIG_KEY = "phylomodel_params"
BASEMODEL_KEY = "basemodel"

HISTOGRAMS_FOLDER='code_histograms'
HISTOGRAMS_FILE="histograms.pkl"