model:
  base_learning_rate: 1.0e-06
  target: scripts.models.phyloautoencoder.PhyloVQVAE
  project: CUB-PhyloNN
  params:
    ckpt_path: /home/mridul/debug/taming-transformers/logs/2023-02-20T15-35-06_CUB-VQGANcub_segmented_white_padding_bb_crop_aug_epoch_567/checkpoints/last.ckpt
    # ckpt_path: /home/mridul/debug/taming-transformers/logs/2023-02-17T19-30-32_CUB-VQGANcub_segmented_white_padding_bb_crop/checkpoints/last.ckpt
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: scripts.modules.losses.DummyLoss
    phylomodel_params:
      embed_dim: 16
      n_embed: 64
      n_phylolevels: 4
      n_levels_non_attribute: 16
      codes_per_phylolevel: 8
      n_phylo_channels: 64
      verbose: false
      ch: 128
      resolution: 16
      in_channels: 256
      out_ch: 256
      n_mlp_layers: 1
      lossconfig:
        target: scripts.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
        params:
          codebook_weight: 1.0
          disc_in_channels: 0
          disc_num_layers: 0
          disc_weight: 0.0
          disc_factor: 0.0
          perceptual_weight: 0.0
          disc_start: 10000
      lossconfig_phylo:
        target: scripts.modules.losses.phyloloss.PhyloLoss
        params:
          phylo_weight: 0.1
          fc_layers: 1
          beta: 0.5
          phyloDistances_string: 0.93,0.83,0.63
          phylogenyconfig:
            target: scripts.data.phylogeny.PhylogenyCUB
            params:
              filePath: /fastscratch/mridul/cub_190_split_resized/official/CUB_200_2011/
          verbose: false
      lossconfig_kernelorthogonality:
        target: scripts.modules.losses.orthogonalloss.OrthogonalLoss
        params:
          weight: 1.0
          padding: 0
          stride: 1
      lossconfig_adversarial:
        target: scripts.modules.losses.adversarialloss.AdversarialLoss
        params:
          weight: 0.1
          beta: 0.7
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 10
    num_workers: 8
    train:
      target: scripts.data.custom.CustomTrain
      params:
        training_images_list_file: /fastscratch/mridul/cub_190_split_resized/official/CUB_200_2011/train_segmented_white_background_bb_crop_256.txt
        size: 256
        add_labels: true
    validation:
      target: scripts.data.custom.CustomTest
      params:
        test_images_list_file: /fastscratch/mridul/cub_190_split_resized/official/CUB_200_2011/test_segmented_white_background_bb_crop_256.txt
        size: 256
        add_labels: true


